name: memcache-debugging
services:
  mywebapp:
    type: php:7.3
    via: nginx
    ssl: false
    webroot: web
    build_as_root:
      - apt-get update -y && apt-get install -y libmemcached-dev
      - yes '' | pecl install -f memcache
      - docker-php-ext-enable memcache
  memcached:
    type: memcached:1.5.12
    portforward: true